/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package usuario;

import acfarmsystemv2.telaDeInicio.*;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Gustavo
 */
public final class TelaDeInicioUsuario extends javax.swing.JFrame {

    /**
     * Creates new form TelaDeIncio
     */
    public TelaDeInicioUsuario() {
        initComponents();
        readJTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCadastrarUsuario = new javax.swing.JButton();
        jButtonVoltarAoTelaDeInicio = new javax.swing.JButton();
        jButtonDeletarUsuario = new javax.swing.JButton();
        jButtonAtualizarUsuario = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableUsuarios = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCadastrarUsuario.setBorder(null);
        jButtonCadastrarUsuario.setBorderPainted(false);
        jButtonCadastrarUsuario.setContentAreaFilled(false);
        jButtonCadastrarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCadastrarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCadastrarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 187, 260, 45));

        jButtonVoltarAoTelaDeInicio.setBorder(null);
        jButtonVoltarAoTelaDeInicio.setBorderPainted(false);
        jButtonVoltarAoTelaDeInicio.setContentAreaFilled(false);
        jButtonVoltarAoTelaDeInicio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltarAoTelaDeInicio.setDefaultCapable(false);
        jButtonVoltarAoTelaDeInicio.setFocusPainted(false);
        jButtonVoltarAoTelaDeInicio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarAoTelaDeInicioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarAoTelaDeInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 40, 20));

        jButtonDeletarUsuario.setToolTipText("");
        jButtonDeletarUsuario.setBorder(null);
        jButtonDeletarUsuario.setBorderPainted(false);
        jButtonDeletarUsuario.setContentAreaFilled(false);
        jButtonDeletarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonDeletarUsuario.setFocusPainted(false);
        jButtonDeletarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonDeletarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(54, 302, 260, 45));

        jButtonAtualizarUsuario.setBorder(null);
        jButtonAtualizarUsuario.setBorderPainted(false);
        jButtonAtualizarUsuario.setContentAreaFilled(false);
        jButtonAtualizarUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonAtualizarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonAtualizarUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(55, 417, 260, 45));

        jTableUsuarios.setBackground(new java.awt.Color(15, 42, 61));
        jTableUsuarios.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTableUsuarios.setForeground(new java.awt.Color(255, 255, 255));
        jTableUsuarios.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome", "ID", "Nivel de Acesso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableUsuarios.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jTableUsuarios.setGridColor(new java.awt.Color(255, 255, 255));
        jTableUsuarios.setRowHeight(30);
        jTableUsuarios.setSelectionForeground(new java.awt.Color(15, 42, 61));
        jTableUsuarios.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTableUsuarios);
        if (jTableUsuarios.getColumnModel().getColumnCount() > 0) {
            jTableUsuarios.getColumnModel().getColumn(0).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(1).setResizable(false);
            jTableUsuarios.getColumnModel().getColumn(2).setResizable(false);
        }

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 80, 450, 490));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_tela_de_usuario.png"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 640));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCadastrarUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaDeCadastroDeUsuario().setVisible(true);
    }//GEN-LAST:event_jButtonCadastrarUsuarioActionPerformed

    private void jButtonVoltarAoTelaDeInicioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarAoTelaDeInicioActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Fechar tela
        new TelaDeInicio().setVisible(true);
    }//GEN-LAST:event_jButtonVoltarAoTelaDeInicioActionPerformed

    private void jButtonDeletarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Fechar tela
        new TelaDeRemocaoDeUsuario().setVisible(true);
    }//GEN-LAST:event_jButtonDeletarUsuarioActionPerformed

    private void jButtonAtualizarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose();
        new TelaDeAtualizacaoDeUsuario().setVisible(true);
    }//GEN-LAST:event_jButtonAtualizarUsuarioActionPerformed

    public void readJTable(){
        DefaultTableModel modelo = (DefaultTableModel) jTableUsuarios.getModel();
        ControleUsuario controleUsuario = new ControleUsuario();
        
        for (Usuario u: controleUsuario.readUsuario()){
            modelo.addRow(new Object[]{u.getNome(),u.getId(), u.getNivelDeAcesso()});
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizarUsuario;
    private javax.swing.JButton jButtonCadastrarUsuario;
    private javax.swing.JButton jButtonDeletarUsuario;
    private javax.swing.JButton jButtonVoltarAoTelaDeInicio;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableUsuarios;
    // End of variables declaration//GEN-END:variables
}
