/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package usuario;

import javax.swing.JOptionPane;

/**
 *
 * @author Gustavo
 */
public class TelaDeCadastroDeUsuario extends javax.swing.JFrame {

    private ControleUsuario usuario = new ControleUsuario();
    private String nivelDeAcesso;

    /**
     * Creates new form TelaDeCadastroDeUsuario
     */
    public TelaDeCadastroDeUsuario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botaoNivelDeAcesso = new javax.swing.ButtonGroup();
        jTextFieldNomeUsuario = new javax.swing.JTextField();
        jPasswordSenhaDoUsuario = new javax.swing.JPasswordField();
        jButtonConfirmarCadastroDeUsuario1 = new javax.swing.JButton();
        jButtonCancelarCadastroDeUsuario = new javax.swing.JButton();
        jRadioAcessoComum = new javax.swing.JRadioButton();
        jRadioAcessoMaster = new javax.swing.JRadioButton();
        jButtonVoltarAoTelaDeUsuario = new javax.swing.JButton();
        jLabelIMGCadastroDeUsuario = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTextFieldNomeUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jTextFieldNomeUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jTextFieldNomeUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jTextFieldNomeUsuario.setBorder(null);
        getContentPane().add(jTextFieldNomeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(39, 276, 307, 30));
        jTextFieldNomeUsuario.getAccessibleContext().setAccessibleName("");

        jPasswordSenhaDoUsuario.setBackground(new java.awt.Color(255, 255, 255));
        jPasswordSenhaDoUsuario.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jPasswordSenhaDoUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jPasswordSenhaDoUsuario.setBorder(null);
        getContentPane().add(jPasswordSenhaDoUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(41, 379, 307, 30));

        jButtonConfirmarCadastroDeUsuario1.setBorder(null);
        jButtonConfirmarCadastroDeUsuario1.setBorderPainted(false);
        jButtonConfirmarCadastroDeUsuario1.setContentAreaFilled(false);
        jButtonConfirmarCadastroDeUsuario1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonConfirmarCadastroDeUsuario1.setFocusPainted(false);
        jButtonConfirmarCadastroDeUsuario1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonConfirmarCadastroDeUsuario1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonConfirmarCadastroDeUsuario1, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 510, 280, 40));

        jButtonCancelarCadastroDeUsuario.setBorder(null);
        jButtonCancelarCadastroDeUsuario.setBorderPainted(false);
        jButtonCancelarCadastroDeUsuario.setContentAreaFilled(false);
        jButtonCancelarCadastroDeUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCancelarCadastroDeUsuario.setFocusable(false);
        jButtonCancelarCadastroDeUsuario.setRequestFocusEnabled(false);
        jButtonCancelarCadastroDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarCadastroDeUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCancelarCadastroDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 562, 280, 38));

        jRadioAcessoComum.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jRadioAcessoComum.setForeground(new java.awt.Color(255, 255, 255));
        jRadioAcessoComum.setText("Comum");
        jRadioAcessoComum.setBorder(null);
        jRadioAcessoComum.setContentAreaFilled(false);
        jRadioAcessoComum.setFocusable(false);
        jRadioAcessoComum.setRequestFocusEnabled(false);
        jRadioAcessoComum.setRolloverEnabled(false);
        jRadioAcessoComum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAcessoComumActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioAcessoComum, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 120, 20));

        jRadioAcessoMaster.setFont(new java.awt.Font("Arial Black", 0, 20)); // NOI18N
        jRadioAcessoMaster.setForeground(new java.awt.Color(255, 255, 255));
        jRadioAcessoMaster.setText("Master");
        jRadioAcessoMaster.setBorder(null);
        jRadioAcessoMaster.setContentAreaFilled(false);
        jRadioAcessoMaster.setFocusable(false);
        jRadioAcessoMaster.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioAcessoMasterActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioAcessoMaster, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 170, 120, 20));

        jButtonVoltarAoTelaDeUsuario.setBorder(null);
        jButtonVoltarAoTelaDeUsuario.setBorderPainted(false);
        jButtonVoltarAoTelaDeUsuario.setContentAreaFilled(false);
        jButtonVoltarAoTelaDeUsuario.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonVoltarAoTelaDeUsuario.setDefaultCapable(false);
        jButtonVoltarAoTelaDeUsuario.setFocusPainted(false);
        jButtonVoltarAoTelaDeUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonVoltarAoTelaDeUsuarioActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonVoltarAoTelaDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 20, 40, 25));

        jLabelIMGCadastroDeUsuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/img_tela_de_cadastro_de_usuario.png"))); // NOI18N
        getContentPane().add(jLabelIMGCadastroDeUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonCancelarCadastroDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarCadastroDeUsuarioActionPerformed
        // TODO add your handling code here:
        jTextFieldNomeUsuario.setText("");
        jPasswordSenhaDoUsuario.setText("");
    }//GEN-LAST:event_jButtonCancelarCadastroDeUsuarioActionPerformed

    private void jButtonConfirmarCadastroDeUsuario1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonConfirmarCadastroDeUsuario1ActionPerformed
        // TODO add your handling code here:
        cadastrarUsuario();
    }//GEN-LAST:event_jButtonConfirmarCadastroDeUsuario1ActionPerformed

    private void jRadioAcessoMasterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAcessoMasterActionPerformed
        // TODO add your handling code here:
        nivelDeAcesso = "M";
    }//GEN-LAST:event_jRadioAcessoMasterActionPerformed

    private void jRadioAcessoComumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioAcessoComumActionPerformed
        // TODO add your handling code here:
        nivelDeAcesso = "C";
    }//GEN-LAST:event_jRadioAcessoComumActionPerformed

    private void jButtonVoltarAoTelaDeUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonVoltarAoTelaDeUsuarioActionPerformed
        // TODO add your handling code here:
        this.dispose(); //Fechar tela
        new TelaDeInicioUsuario().setVisible(true);
    }//GEN-LAST:event_jButtonVoltarAoTelaDeUsuarioActionPerformed

    public void cadastrarUsuario() {
        //setId(Integer.parseInt(txtId.getText()));

        // Coleta os dados da interface gráfica
        String nome = jTextFieldNomeUsuario.getText();
        String senha = new String(jPasswordSenhaDoUsuario.getPassword());
        String nivelAcesso = nivelDeAcesso;
        botaoNivelDeAcesso.add(jRadioAcessoComum);
        botaoNivelDeAcesso.add(jRadioAcessoMaster);
        
        if (jPasswordSenhaDoUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "a Senha não pode ser Validada");
            jPasswordSenhaDoUsuario.requestFocus();
            return;
        }

        if (jTextFieldNomeUsuario.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "a Senha não pode ser Validada");
            jTextFieldNomeUsuario.requestFocus();
            return;
        }

        if (botaoNivelDeAcesso.equals("")) {
            JOptionPane.showMessageDialog(null, "Adicione o nivel de Acesso");
        }

        if (botaoNivelDeAcesso.equals(jRadioAcessoComum) && botaoNivelDeAcesso.equals(jRadioAcessoMaster)) {
            JOptionPane.showMessageDialog(null, "Escolha apenas um nivel de acesso");
        }

        // Define os dados no objeto ControleUsuario
        usuario.usuario.setNome(nome);
        usuario.usuario.setSenha(senha);
        usuario.usuario.setNivelDeAcesso(nivelAcesso);

        // Chama o método cadastrar do ControleUsuario
        String msg = usuario.cadastrar(ControleUsuario.INCLUSAO);

        // Exibe mensagem para o usuario
        JOptionPane.showMessageDialog(this, msg);

        // Limpa os campos
        jTextFieldNomeUsuario.setText("");
        jPasswordSenhaDoUsuario.setText("");
        
    }
    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup botaoNivelDeAcesso;
    private javax.swing.JButton jButtonCancelarCadastroDeUsuario;
    private javax.swing.JButton jButtonConfirmarCadastroDeUsuario1;
    private javax.swing.JButton jButtonVoltarAoTelaDeUsuario;
    private javax.swing.JLabel jLabelIMGCadastroDeUsuario;
    private javax.swing.JPasswordField jPasswordSenhaDoUsuario;
    private javax.swing.JRadioButton jRadioAcessoComum;
    private javax.swing.JRadioButton jRadioAcessoMaster;
    private javax.swing.JTextField jTextFieldNomeUsuario;
    // End of variables declaration//GEN-END:variables
}
